# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: FOI უსაფრთხოება
repo_url: https://github.com/foige/security
repo_name: ""
markdown_extensions:
  - attr_list
  - abbr
  - md_in_html
  - tables
  - pymdownx.blocks.details
  - pymdownx.arithmatex
  - pymdownx.blocks.admonition
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
      toc_depth: 4
plugins:
  - material-plausible
  - include-markdown
  - search
  - zip_folders:
      folders:
        - policies/files/foi_security_policy_win
extra:
  analytics:
    provider: plausible
    domain: security.foi.ge
extra_css:
  - assets/stylesheets/extra.css
theme:
  name: material
  font:
    text: Noto Sans Georgian
  palette:
    scheme: slate
  custom_dir: theme
  favicon: assets/brand/images/logo-32x32.png
  logo: assets/brand/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - search.highlight
nav:
  - მთავარი: index.md
#  - გიდი:
#      - guide/prerequisites.md
  - გადაწყვეტები:
      - solutions/index.md
      - "საბაზისო":
          - solutions/passwords.md
          - solutions/mfa.md
      - "ოპერაციული სისტემები":
          - solutions/windows.md
          - solutions/macos.md
          - solutions/ios.md
          - solutions/android.md
      - "ქსელები":
          - solutions/dns.md
          - solutions/vpn.md
  - FOI Security Policy:
      - policies/index.md
      - "გამოყენებული პარამეტრების სია":
          - policies/browser.md
          - policies/windows.md
          - policies/macos.md