# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: FOI უსაფრთხოება
repo_url: https://github.com/foige/security
repo_name: ""
markdown_extensions:
  - attr_list
  - md_in_html
  - tables
  - pymdownx.blocks.details
  - pymdownx.arithmatex
  - pymdownx.blocks.admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: true
      toc_depth: 4
plugins:
  - include-markdown
  - search
  - zip_folders:
      folders:
        - policies/files/foi_security_policy_win
theme:
  name: material
  palette:
    scheme: slate
  custom_dir: theme
  favicon: assets/brand/images/logo-32x32.png
  logo: assets/brand/images/logo.png
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - content.action.edit
    - content.tabs.link
    - content.tooltips
    - search.highlight
nav:
  - მთავარი: index.md
  - გიდი:
      - guide/prerequisites.md
  - გადაწყვეტილებები:
      - solutions/index.md
      - "საბაზისო":
          - solutions/passwords.md
          - solutions/mfa.md
      - "ოპერაციული სისტემები":
          - solutions/windows.md
          - solutions/macos.md
      - "ქსელები":
          - solutions/dns.md
          - solutions/vpn.md
  - FOI Security Policy:
      - policies/index.md
      - "გამოყენებული პარამეტრების სია":
        - policies/browser.md
        - policies/windows.md
        - policies/macos.md
#  - Policies:
#    - Information Security Policy: policies/information-security-policy.md
#    - Data Protection Policy: policies/data-protection-policy.md
#    - Acceptable Use Policy: policies/acceptable-use-policy.md
#  - Procedures:
#    - Incident Response Procedure: procedures/incident-response-procedure.md
#    - Data Breach Procedure: procedures/data-breach-procedure.md
#    - Data Classification Procedure: procedures/data-classification-procedure.md
#  - Standards:
#    - Password Policy: standards/password-policy.md
#    - Encryption Policy: standards/encryption-policy.md
#    - Remote Access Policy: standards/remote-access-policy.md
#  - Guidelines:
#    - Data Classification Guidelines: guidelines/data-classification-guidelines.md
#    - Data Handling Guidelines: guidelines/data-handling-guidelines.md
#    - Data Retention Guidelines: guidelines/data-retention-guidelines.md
#  - Training:
#    - Security Awareness Training: training/security-awareness-training.md
#    - Data Protection Training: training/data-protection-training.md
#  - Resources:
#    - Useful Links: resources/useful-links.md
#    - Glossary: resources/glossary.md
#    - FAQ: resources/faq.md
#  - Blog: blog.md
#  - Search: search.md